# docker-compose.yml
version: "3.4"
services:
  app:
    build: .
    entrypoint: ./wait-for-it.sh db:5432 -t 15 -s --
    environment:
      DEBUG: 1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - data-volume:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data-volume:
