# Generated by Django 2.2.10 on 2020-03-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0063_auto_20200318_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestands',
            name='fee_acceptable',
            field=models.BooleanField(default=False, verbose_name='fee_acceptable'),
            preserve_default=False,
        ),
    ]
